export const ADD_HOMEWORK_STUDENT = 'HOMEWORK/ADD_HOMEWORK_STUDENT';
export const UPDATE_HOMEWORK_STUDENT = 'HOMEWORK/UPDATE_HOMEWORK_STUDENT';
export const GET_HOMEWORK_STUDENT = 'HOMEWORK/GET_HOMEWORK_STUDENT';
export const GET_HOMEWORK_STUDENT_BY_ID = 'HOMEWORK/GET_HOMEWORK_STUDENT_BY_ID';

export const ADDING_HOMEWORK_STUDENT_STARTED = 'HOMEWORK/ADDING_HOMEWORK_STUDENT_STARTED';
export const ADDING_HOMEWORK_STUDENT_SUCCESS = 'HOMEWORK/ADDING_HOMEWORK_STUDENT_SUCCESS';
export const ADDING_HOMEWORK_STUDENT_FAILED = 'HOMEWORK/ADDING_HOMEWORK_STUDENT_FAILED';

export const LOADING_HOMEWORK_STUDENT_STARTED = 'HOMEWORK/LOADING_HOMEWORK_STUDENT_STARTED';
export const LOADING_HOMEWORK_STUDENT_SUCCESS = 'HOMEWORK/LOADING_HOMEWORK_STUDENT_SUCCESS';
export const LOADING_HOMEWORK_STUDENT_FAILED = 'HOMEWORK/LOADING_HOMEWORK_STUDENT_FAILED';

export const LOADING_HOMEWORK_STUDENT_BY_ID_STARTED = 'HOMEWORK/LOADING_HOMEWORK_STUDENT_BY_ID_STARTED';
export const LOADING_HOMEWORK_STUDENT_BY_ID_SUCCESS = 'HOMEWORK/LOADING_HOMEWORK_STUDENT_BY_ID_SUCCESS';
export const LOADING_HOMEWORK_STUDENT_BY_ID_FAILED = 'HOMEWORK/LOADING_HOMEWORK_STUDENT_BY_ID_FAILED';

export const UPDATING_HOMEWORK_STUDENT_STARTED = 'HOMEWORK/UPDATING_HOMEWORK_STUDENT_STARTED';
export const UPDATING_HOMEWORK_STUDENT_SUCCESS = 'HOMEWORK/UPDATING_HOMEWORK_STUDENT_SUCCESS';
export const UPDATING_HOMEWORK_STUDENT_FAILED = 'HOMEWORK/UPDATING_HOMEWORK_STUDENT_FAILED';

export const CLEAR_LOADED = 'HOMEWORK_STUDENT/CLEAR_LOADED';
export const CLEAR_ERROR = 'HOMEWORK_STUDENT/CLEAR_ERROR';
