export const FETCH_HOMEWORK_BY_ID = 'HOMEWORK/FETCH_HOMEWORK_BY_ID';
export const LOADING_HOMEWORK_STARTED_BY_ID = 'HOMEWORK/LOADING_HOMEWORK_STARTED_BY_ID';
export const LOADING_HOMEWORK_FINISHED_BY_ID = 'HOMEWORK/LOADING_HOMEWORK_FINISHED_BY_ID';
export const LOADING_HOMEWORK_FAILED_BY_ID = 'HOMEWORK/LOADING_HOMEWORK_FAILED_BY_ID';

export const ADD_HOMEWORK = 'HOMEWORK/ADD_HOMEWORK';
export const ADD_HOMEWORK_STARTED = 'HOMEWORK/ADD_HOMEWORK_STARTED';
export const ADD_HOMEWORK_FINISHED = 'HOMEWORK/ADD_HOMEWORK_FINISHED';
export const ADD_HOMEWORK_FAILED = 'HOMEWORK/ADD_HOMEWORK_FAILED';

export const EDIT_HOMEWORK = 'HOMEWORK/EDIT_HOMEWORK';
export const EDIT_HOMEWORK_STARTED = 'HOMEWORK/EDIT_HOMEWORK/STARTED';
export const EDIT_HOMEWORK_FINISHED = 'HOMEWORK/EDIT_HOMEWORK/FINISHED';
export const EDIT_HOMEWORK_FAILED = 'HOMEWORK/EDIT_HOMEWORK_FAILED';

export const CLEAR_LOADED = 'HOMEWORK/CLEAR_LOADED';
export const CLEAR_ERROR = 'HOMEWORK/CLEAR_ERROR';