export const ADD_HOMEWORK = 'HOMEWORK/ADD_HOMEWORK';
export const UPDATE_HOMEWORK = 'HOMEWORK/UPDATE_HOMEWORK';
export const GET_HOMEWORK = 'HOMEWORK/GET_HOMEWORK';

export const ADDING_HOMEWORK_STARTED = 'HOMEWORK/ADDING_HOMEWORK_STARTED';
export const ADDING_HOMEWORK_SUCCESS = 'HOMEWORK/ADDING_HOMEWORK_SUCCESS';
export const ADDING_HOMEWORK_FAILED = 'HOMEWORK/ADDING_HOMEWORK_FAILED';

export const LOADING_HOMEWORK_STARTED = 'HOMEWORK/LOADING_HOMEWORK_STARTED';
export const LOADING_HOMEWORK_SUCCESS = 'HOMEWORK/LOADING_HOMEWORK_SUCCESS';
export const LOADING_HOMEWORK_FAILED = 'HOMEWORK/LOADING_HOMEWORK_FAILED';

export const UPDATING_HOMEWORK_STARTED = 'HOMEWORK/UPDATING_HOMEWORK_STARTED';
export const UPDATING_HOMEWORK_SUCCESS = 'HOMEWORK/UPDATING_HOMEWORK_SUCCESS';
export const UPDATING_HOMEWORK_FAILED = 'HOMEWORK/UPDATING_HOMEWORK_FAILED';

export const CLEAR_LOADED = 'HOMEWORK/CLEAR_LOADED';
export const CLEAR_ERROR = 'HOMEWORK/CLEAR_ERROR';
