export const CREATE_ATTACHMENTS = 'ATTACHMENTS/CREATE_ATTACHMENTS';
export const CREATING_ATTACHMENTS_STARTED = 'ATTACHMENTS/CREATING_ATTACHMENTS_STARTED';
export const CREATING_ATTACHMENTS_SUCCEED = 'ATTACHMENTS/CREATING_ATTACHMENTS_SUCCEED';
export const CREATING_ATTACHMENTS_FAILED = 'ATTACHMENTS/CREATING_ATTACHMENTS_FAILED';

export const FETCH_ATTACHMENTS = 'ATTACHMENTS/FETCH_ATTACHMENTS';
export const FETCHING_ATTACHMENTS_STARTED = 'ATTACHMENTS/FETCHING_ATTACHMENTS_STARTED';
export const FETCHING_ATTACHMENTS_SUCCEED = 'ATTACHMENTS/FETCHING_ATTACHMENTS_SUCCEED';
export const FETCHING_ATTACHMENTS_FAILED = 'ATTACHMENTS/FETCHING_ATTACHMENTS_FAILED';

export const FETCH_ATTACHMENT_BY_ID = 'ATTACHMENTS/FETCH_ATTACHMENT_BY_ID';
export const FETCHING_ATTACHMENT_BY_ID_STARTED = 'ATTACHMENTS/FETCHING_ATTACHMENT_BY_ID_STARTED';
export const FETCHING_ATTACHMENT_BY_ID_SUCCEED = 'ATTACHMENTS/FETCHING_ATTACHMENT_BY_ID_SUCCEED';
export const FETCHING_ATTACHMENT_BY_ID_FAILED = 'ATTACHMENTS/FETCHING_ATTACHMENT_BY_ID_FAILED';

export const CLEAR_LOADED = 'ATTACHMENT/CLEAR_LOADED';