export * from './counter';
export * from './student-profile';
export * from './edit-group';
export * from './support';
export * from './start-group';
export * from './auth';
export * from './routes';
export * from './header';
export * from './edit-students-details';
export * from './validation'
export * from './list-of-groups';
export * from './list-of-students';
export * from './schedule-student';
export * from './not-found';
export * from './edit-secretarys-details';