export const COUNTER_INCREMENT = 'COUNTER/INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER/DECREMENT';
export const FETCH_COUNTER = 'COUNTER/FETCH_COUNTER';
export const COUNTER_LOADING_STARTED = 'COUNTER/LOADING_STARTED';
export const COUNTER_LOADING_FINISHED = 'COUNTER/LOADING_FINISHED';
export const COUNTER_LOADING_FAILED = 'COUNTER/LOADING_FAILED';
