export const   CREATE_STUDENTS_CLASSBOOK             = 'EXPORT/CREATE_STUDENTS_CLASSBOOK';
export const CREATING_STUDENTS_CLASSBOOK_STARTED     = 'EXPORT/CREATING_STUDENTS_CLASSBOOK_STARTED';
export const CREATING_STUDENTS_CLASSBOOK_FINISHED    = 'EXPORT/CREATING_STUDENTS_CLASSBOOK_FINISHED';
export const CREATING_STUDENTS_CLASSBOOK_FAILED      = 'EXPORT/CREATING_STUDENTS_CLASSBOOK_FAILED';

export const   CREATE_STUDENTS_RESULTS               = 'EXPORT/CREATE_STUDENTS_RESULTS';
export const CREATING_STUDENTS_RESULTS_STARTED       = 'EXPORT/CREATING_STUDENTS_RESULTS_STARTED';
export const CREATING_STUDENTS_RESULTS_FINISHED      = 'EXPORT/CREATING_STUDENTS_RESULTS_FINISHED';
export const CREATING_STUDENTS_RESULTS_FAILED        = 'EXPORT/CREATING_STUDENTS_RESULTS_FAILED';

export const   CREATE_STUDENT_CLASSBOOK              = 'EXPORT/CREATE_STUDENT_CLASSBOOK';
export const CREATING_STUDENT_CLASSBOOK_STARTED      = 'EXPORT/CREATING_STUDENT_CLASSBOOK_STARTED';
export const CREATING_STUDENT_CLASSBOOK_FINISHED     = 'EXPORT/CREATING_STUDENT_CLASSBOOK_FINISHED';
export const CREATING_STUDENT_CLASSBOOK_FAILED       = 'EXPORT/CREATING_STUDENT_CLASSBOOK_FAILED';

export const   CREATE_STUDENT_RESULTS                = 'EXPORT/CREATE_STUDENT_RESULTS';
export const CREATING_STUDENT_RESULTS_STARTED        = 'EXPORT/CREATING_STUDENT_RESULTS_STARTED';
export const CREATING_STUDENT_RESULTS_FINISHED       = 'EXPORT/CREATING_STUDENT_RESULTS_FINISHED';
export const CREATING_STUDENT_RESULTS_FAILED         = 'EXPORT/CREATING_STUDENT_RESULTS_FAILED';

export const   CREATE_STUDENT_GROUP_RESULTS          = 'EXPORT/CREATE_STUDENT_GROUP_RESULTS';
export const CREATING_STUDENT_GROUP_RESULTS_STARTED  = 'EXPORT/CREATING_STUDENT_GROUP_RESULTS_STARTED';
export const CREATING_STUDENT_GROUP_RESULTS_FINISHED = 'EXPORT/CREATING_STUDENT_GROUP_RESULTS_FINISHED';
export const CREATING_STUDENT_GROUP_RESULTS_FAILED   = 'EXPORT/CREATING_STUDENT_GROUP_RESULTS_FAILED';

export const CLEAR_LOADED                            = 'EXPORT/CLEAR_LOADED';