export const SEND_GROUPS = 'IMPORT/SEND_GROUPS';
export const SENDING_GROUPS_STARTED = 'IMPORT/SENDING_GROUPS_STARTED';
export const SENDING_GROUPS_SUCCESS = 'IMPORT/SENDING_GROUPS_FINISHED';
export const SENDING_GROUPS_FAILED = 'IMPORT/SENDING_GROUPS_FAILED'

export const SEND_STUDENTS = 'IMPORT/SEND_STUDENTS';
export const SENDING_STUDENTS_STARTED = 'IMPORT/SENDING_STUDENTS_STARTED';
export const SENDING_STUDENTS_SUCCESS = 'IMPORT/SENDING_STUDENTS_FINISHED';
export const SENDING_STUDENTS_FAILED = 'IMPORT/SENDING_STUDENTS_FAILED';

export const SEND_THEMES = 'IMPORT/SEND_THEMES';
export const SENDING_THEMES_STARTED = 'IMPORT/SENDING_THEMES_STARTED';
export const SENDING_THEMES_SUCCESS = 'IMPORT/SENDING_THEMES_FINISHED';
export const SENDING_THEMES_FAILED = 'IMPORT/SENDING_THEMES_FAILED';

export const CLEAR_LOADED = 'IMPORT/CLEAR_LOADED';