export const LOAD_STUDENTS = 'STUDENTS/LOAD_STUDENTS';
export const LOADING_STUDENTS_SUCCEED = 'STUDENTS/LOADING_STUDENTS_SUCCEED';

export const LOAD_ACTIVE_STUDENTS = 'STUDENTS/LOAD_ACTIVE';
export const LOADING_ACTIVE_SUCCEED = 'STUDENTS/LOADING_ACTIVE_SUCCEED';

export const LOAD_STUDENT_BY_ID = 'STUDENTS/LOAD_STUDENT_BY_ID';
export const LOADING_BY_ID_SUCCEED = 'STUDENTS/LOADING_BY_ID_SUCCEED';

export const LOAD_STUDENT_GROUPS = 'STUDENTS/LOAD_STUDENT_GROUPS';
export const LOADING_STUDENT_GROUPS_SUCCEED = 'STUDENTS/LOADING_STUDENT_GROUPS_SUCCEED';

export const ADD_STUDENT = 'STUDENTS/ADD_STUDENT';
export const ADDING_STUDENT_SUCCEED = 'STUDENTS/ADDING_SUCCEED';

export const EDIT_STUDENT = 'STUDENTS/EDIT_STUDENT';
export const EDITING_STUDENT_SUCCEED = 'STUDENTS/EDITING_SUCCEED';

export const REMOVE_STUDENT = 'STUDENT/REMOVE_STUDENT';
export const REMOVING_STUDENT_SUCCEED = 'STUDENT/REMOVING_SUCCEED';

export const LOADING_STARTED = 'STUDENTS/LOADING_STARTED';
export const LOADING_FAILED = 'STUDENTS/LOADING_FAILED';
