export const LOAD_STUDENTS = 'STUDENTS/LOAD_STUDENTS';
export const LOADING_STUDENTS_STARTED = 'STUDENTS/LOADING_STARTED';
export const LOADING_STUDENTS_SUCCESS = 'STUDENTS/LOADING_SUCCEED';
export const LOADING_STUDENTS_FAILED = 'STUDENTS/LOADING_FAILED';
