export const LOAD_STUDENTS = 'STUDENTS/LOAD_STUDENTS';
export const LOADING_STUDENTS_STARTED = 'STUDENTS/LOADING_STUDENTS_STARTED';
export const LOADING_STUDENTS_SUCCEED = 'STUDENTS/LOADING_STUDENTS_SUCCEED';
export const LOADING_STUDENTS_FAILED = 'STUDENTS/LOADING_STUDENTS_FAILED';

export const LOAD_ACTIVE_STUDENTS = 'STUDENTS/LOAD_ACTIVE';
export const LOADING_ACTIVE_STARTED = 'STUDENTS/LOADING_ACTIVE_STARTED';
export const LOADING_ACTIVE_SUCCEED = 'STUDENTS/LOADING_ACTIVE_SUCCEED';
export const LOADING_ACTIVE_FAILED = 'STUDENTS/LOADING_ACTIVE_FAILED';

export const LOAD_STUDENT_BY_ID = 'STUDENTS/LOAD_STUDENT_BY_ID';
export const LOADING_BY_ID_STARTED = 'STUDENTS/LOADING_BY_ID_STARTED';
export const LOADING_BY_ID_SUCCEED = 'STUDENTS/LOADING_BY_ID_SUCCEED';
export const LOADING_BY_ID_FAILED = 'STUDENTS/LOADING_BY_ID_FAILED';

export const LOAD_STUDENT_GROUPS = 'STUDENTS/LOAD_STUDENT_GROUPS';
export const LOADING_STUDENT_GROUPS_STARTED = 'STUDENTS/LOADING_STUDENT_GROUPS_STARTED';
export const LOADING_STUDENT_GROUPS_SUCCEED = 'STUDENTS/LOADING_STUDENT_GROUPS_SUCCEED';
export const LOADING_STUDENT_GROUPS_FAILED = 'STUDENTS/LOADING_STUDENT_GROUPS_FAILED';

export const ADD_STUDENT = 'STUDENTS/ADD_STUDENT';
export const ADDING_STUDENT_STARTED = 'STUDENTS/ADDING_STARTED';
export const ADDING_STUDENT_SUCCEED = 'STUDENTS/ADDING_SUCCEED';
export const ADDING_STUDENT_FAILED = 'STUDENTS/ADDING_FAILED';

export const EDIT_STUDENT = 'STUDENTS/EDIT_STUDENT';
export const EDITING_STUDENT_STARTED = 'STUDENTS/EDITING_STARTED';
export const EDITING_STUDENT_SUCCEED = 'STUDENTS/EDITING_SUCCEED';
export const EDITING_STUDENT_FAILED = 'STUDENTS/EDITING_FAILED';

export const REMOVE_STUDENT = 'STUDENT/REMOVE_STUDENT';
export const REMOVING_STUDENT_STARTED = 'STUDENT/REMOVING_STARTED';
export const REMOVING_STUDENT_SUCCEED = 'STUDENT/REMOVING_SUCCEED';
export const REMOVING_STUDENT_FAILED = 'STUDENT/REMOVING_FAILED';

export const REACTIVATE_STUDENT = 'STUDENT/REACTIVATE_STUDENT';
export const REACTIVATING_STUDENT_STARTED = 'STUDENT/REACTIVATING_STARTED';
export const REACTIVATING_STUDENT_SUCCEED = 'STUDENT/REACTIVATING_SUCCEED';
export const REACTIVATING_STUDENT_FAILED = 'STUDENT/REACTIVATING_FAILED';

export const CLEAR_LOADED = 'STUDENTS/CLEAR_LOADED';
export const CLEAR_ERROR = 'STUDENTS/CLEAR_ERROR';
