export const CREATE_STUDENTS_CLASSBOOK = 'DASHBOARD/CREATE_STUDENTS_CLASSBOOK';
export const CREATING_STUDENTS_CLASSBOOK_STARTED = 'DASHBOARD/CREATING_STUDENTS_CLASSBOOK_STARTED';
export const CREATING_STUDENTS_CLASSBOOK_FINISHED = 'DASHBOARD/CREATING_STUDENTS_CLASSBOOK_FINISHED';
export const CREATING_STUDENTS_CLASSBOOK_FAILED = 'DASHBOARD/CREATING_STUDENTS_CLASSBOOK_FAILED';

export const CREATE_STUDENTS_RESULTS = 'DASHBOARD/CREATE_STUDENTS_RESULTS';
export const CREATING_STUDENTS_RESULTS_STARTED = 'DASHBOARD/CREATING_STUDENTS_RESULTS_STARTED';
export const CREATING_STUDENTS_RESULTS_FINISHED = 'DASHBOARD/CREATING_STUDENTS_RESULTS_FINISHED';
export const CREATING_STUDENTS_RESULTS_FAILED = 'DASHBOARD/CREATING_STUDENTS_RESULTS_FAILED';

export const CREATE_STUDENT_RESULTS = 'DASHBOARD/CREATE_STUDENT_RESULTS';
export const CREATING_STUDENT_RESULTS_STARTED = 'DASHBOARD/CREATING_STUDENT_RESULTS_STARTED';
export const CREATING_STUDENT_RESULTS_FINISHED = 'DASHBOARD/CREATING_STUDENT_RESULTS_FINISHED';
export const CREATING_STUDENT_RESULTS_FAILED = 'DASHBOARD/CREATING_STUDENT_RESULTS_FAILED';

export const CREATE_STUDENT_CLASSBOOK = 'DASHBOARD/CREATE_STUDENT_CLASSBOOK';
export const CREATING_STUDENT_CLASSBOOK_STARTED = 'DASHBOARD/CREATING_STUDENT_CLASSBOOK_STARTED';
export const CREATING_STUDENT_CLASSBOOK_FINISHED = 'DASHBOARD/CREATING_STUDENT_CLASSBOOK_FINISHED';
export const CREATING_STUDENT_CLASSBOOK_FAILED = 'DASHBOARD/CREATING_STUDENT_CLASSBOOK_FAILED';

export const CREATE_STUDENT_GROUP_RESULTS = 'DASHBOARD/CREATE_STUDENT_GROUP_RESULTS';
export const CREATING_STUDENT_GROUP_RESULTS_STARTED = 'DASHBOARD/CREATING_STUDENT_GROUP_RESULTS_STARTED';
export const CREATING_STUDENT_GROUP_RESULTS_FINISHED = 'DASHBOARD/CREATING_STUDENT_GROUP_RESULTS_FINISHED';
export const CREATING_STUDENT_GROUP_RESULTS_FAILED = 'DASHBOARD/CREATING_STUDENT_GROUP_RESULTS_FAILED';

export const CLEAR_LOADED = 'DASHBOARD/CLEAR_LOADED';