export const ADD_STUDENT_GROUP = 'STUDENT_GROUPS/ADD_STUDENT_GROUP';
export const ADDING_STUDENT_GROUP_STARTED = 'STUDENT_GROUPS/ADDING_STUDENT_GROUP_STARTED';
export const ADDING_STUDENT_GROUP_SUCCEED = 'STUDENT_GROUPS/ADDING_STUDENT_GROUP_SUCCEED';
export const ADDING_STUDENT_GROUP_FAILED = 'STUDENT_GROUPS/ADDING_STUDENT_GROUP_FAILED';

export const LOAD_STUDENT_GROUPS = 'STUDENT_GROUPS/LOAD_STUDENT_GROUPS';
export const LOADING_STUDENT_GROUPS_STARTED = 'STUDENT_GROUPS/LOADING_STUDENT_GROUPS_STARTED';
export const LOADING_STUDENT_GROUPS_SUCCEED = 'STUDENT_GROUPS/LOADING_STUDENT_GROUPS_SUCCEED';
export const LOADING_STUDENT_GROUPS_FAILED = 'STUDENT_GROUPS/LOADING_STUDENT_GROUPS_FAILED';

export const LOAD_STUDENT_GROUP_BY_ID = 'STUDENT_GROUPS/LOAD_BY_ID_STUDENT_GROUP';
export const LOADING_BY_ID_STUDENT_GROUP_STARTED = 'STUDENT_GROUPS/LOADING_BY_ID_STUDENT_GROUP_STARTED';
export const LOADING_BY_ID_STUDENT_GROUP_SUCCEED = 'STUDENT_GROUPS/LOADING_BY_ID_STUDENT_GROUP_SUCCEED';
export const LOADING_BY_ID_STUDENT_GROUP_FAILED = 'STUDENT_GROUPS/LOADING_BY_ID_STUDENT_GROUP_FAILED';

export const EDIT_STUDENT_GROUP = 'STUDENT_GROUPS/EDIT_STUDENT_GROUP';
export const EDITING_STUDENT_GROUP_STARTED = 'STUDENT_GROUPS/EDITING_STUDENT_GROUP_STARTED';
export const EDITING_STUDENT_GROUP_SUCCEED = 'STUDENT_GROUPS/EDITING_STUDENT_GROUP_SUCCEED';
export const EDITING_STUDENT_GROUP_FAILED = 'STUDENT_GROUPS/EDITING_STUDENT_GROUP_FAILED';