export const LOAD_MENTORS = 'MENTORS/LOAD';
export const LOADING_MENTORS_STARTED = 'MENTORS/LOADING_STARTED';
export const LOADING_MENTORS_SUCCESS = 'MENTORS/LOADING_FINISHED';
export const LOADING_MENTORS_FAILED = 'MENTORS/LOADING_FAILED';
