export const FETCH_MENTORS = 'MENTORS/FETCH_MENTORS';
export const FETCHING_MENTORS_STARTED = 'MENTORS/FETCHING_MENTORS_STARTED';
export const FETCHING_MENTORS_SUCCEED = 'MENTORS/FETCHING_MENTORS_SUCCEED';
export const FETCHING_MENTORS_FAILED = 'MENTORS/FETCHING_MENTORS_FAILED';

export const FETCH_ACTIVE_MENTORS = 'MENTORS/FETCH_ACTIVE';
export const FETCHING_ACTIVE_STARTED = 'MENTORS/FETCHING_ACTIVE_STARTED';
export const FETCHING_ACTIVE_SUCCEED = 'MENTORS/FETCHING_ACTIVE_SUCCEED';
export const FETCHING_ACTIVE_FAILED = 'MENTORS/FETCHING_ACTIVE_FAILED';

export const FETCH_MENTOR_BY_ID = 'MENTORS/FETCH_MENTOR_BY_ID';
export const FETCHING_BY_ID_STARTED = 'MENTORS/FETCHING_BY_ID_STARTED';
export const FETCHING_BY_ID_SUCCEED = 'MENTORS/FETCHING_BY_ID_SUCCEED';
export const FETCHING_BY_ID_FAILED = 'MENTORS/FETCHING_BY_ID_FAILED';

export const FETCH_MENTOR_GROUPS = 'MENTORS/FETCH_MENTOR_GROUPS';
export const FETCHING_MENTOR_GROUPS_STARTED = 'MENTORS/FETCHING_MENTOR_GROUPS_STARTED';
export const FETCHING_MENTOR_GROUPS_SUCCEED = 'MENTORS/FETCHING_MENTOR_GROUPS_SUCCEED';
export const FETCHING_MENTOR_GROUPS_FAILED = 'MENTORS/FETCHING_MENTOR_GROUPS_FAILED';

export const FETCH_MENTOR_COURSES = 'MENTORS/FETCH_MENTOR_GROUPS';
export const FETCHING_MENTOR_COURSES_STARTED = 'MENTORS/FETCHING_MENTOR_COURSES_STARTED';
export const FETCHING_MENTOR_COURSES_SUCCEED = 'MENTORS/FETCHING_MENTOR_COURSES_SUCCEED';
export const FETCHING_MENTOR_COURSES_FAILED = 'MENTORS/FETCHING_MENTOR_COURSES_FAILED';

export const ADD_MENTOR = 'MENTORS/ADD_MENTOR';
export const ADDING_MENTOR_STARTED = 'MENTORS/ADDING_STARTED';
export const ADDING_MENTOR_SUCCEED = 'MENTORS/ADDING_SUCCEED';
export const ADDING_MENTOR_FAILED = 'MENTORS/ADDING_FAILED';

export const EDIT_MENTOR = 'MENTORS/EDIT_MENTOR';
export const EDITING_MENTOR_STARTED = 'MENTORS/EDITING_STARTED';
export const EDITING_MENTOR_SUCCEED = 'MENTORS/EDITING_SUCCEED';
export const EDITING_MENTOR_FAILED = 'MENTORS/EDITING_FAILED';

export const DELETE_MENTOR = 'MENTOR/DELETE_MENTOR';
export const DELETING_MENTOR_STARTED = 'MENTOR/DELETING_STARTED';
export const DELETING_MENTOR_SUCCEED = 'MENTOR/DELETING_SUCCEED';
export const DELETING_MENTOR_FAILED = 'MENTOR/DELETING_FAILED';

export const CLEAR_LOADED = 'MENTOR/CLEAR_LOADED';