export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_USER = 'CLEAR_USER';

export const REGIST_REQUSTING = 'REGIST_REQUSTING';
export const REGIST_STARTED = 'REGIST_STARTED';
export const REGIST_SUCCESS = 'REGIST_SUCCESS';
export const REGIST_ERROR = 'REGIST_ERROR';

export const FETCH_ASSIGNED = 'FETCH_ASSIGNED';
export const FETCH_ASSIGNED_STARTED = 'FETCH_ASSIGNED_STARTED';
export const FETCH_ASSIGNED_SUCCESS = 'FETCH_ASSIGNED_SUCCESS';
export const FETCH_ASSIGNED_ERROR = 'FETCH_ASSIGNED_ERROR';

export const FETCH_UNASSIGNED = 'FETCH_UNASSIGNED';
export const FETCH_UNASSIGNED_STARTED = 'FETCH_UNASSIGNED_STARTED';
export const FETCH_UNASSIGNED_SUCCESS = 'FETCH_UNASSIGNED_SUCCESS';
export const FETCH_UNASSIGNED_ERROR = 'FETCH_UNASSIGNED_ERROR';

export const NEW_PASSWORD = 'ACCOUNTS/NEW_PASSWORD';
export const NEW_PASSWORD_CREATING_STARTED = 'ACCOUNTS/NEW_PASSWORD_CREATING_STARTED';
export const NEW_PASSWORD_CREATING_SUCCESS = 'ACCOUNTS/NEW_PASSWORD_CREATING_SUCCESS';
export const NEW_PASSWORD_CREATING_FAILED = 'ACCOUNTS/NEW_PASSWORD_CREATING_FAILED';

export const FORGOT_PASSWORD = 'ACCOUNT/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_REQUEST_STARTED = 'ACCOUNT/FORGOT_PASSWORD_REQUEST_STARTED';
export const FORGOT_PASSWORD_REQUEST_SUCCESS = 'ACCOUNT/FORGOT_PASSWORD_REQUEST_SUCCESS';
export const FORGOT_PASSWORD_REQUEST_FAILED = 'ACCOUNT/FORGOT_PASSWORD_REQUEST_FAILED';

export const RESET_PASSWORD = 'ACCOUNT/RESET_PASSWORD';
export const RESET_PASSWORD_REQUEST_STARTED = 'ACCOUNT/RESET_PASSWORD_REQUEST_STARTED';
export const RESET_PASSWORD_REQUEST_SUCCESS = 'ACCOUNT/RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILED = 'ACCOUNT/RESET_PASSWORD_REQUEST_FAILED';

export const CLEAR_LOADED = 'CLEAR_REGISTRATION';