export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_USER = 'CLEAR_USER';

export const REGIST_REQUSTING = 'REGIST_REQUSTING';
export const REGIST_STARTED = 'REGIST_STARTED';
export const REGIST_SUCCESS = 'REGIST_SUCCESS';
export const REGIST_ERROR = 'REGIST_ERROR';

export const FETCH_ASSIGNED = 'FETCH_ASSIGNED';
export const FETCH_ASSIGNED_STARTED = 'FETCH_ASSIGNED_STARTED';
export const FETCH_ASSIGNED_SUCCESS = 'FETCH_ASSIGNED_SUCCESS';
export const FETCH_ASSIGNED_ERROR = 'FETCH_ASSIGNED_ERROR';

export const FETCH_UNASSIGNED = 'FETCH_UNASSIGNED';
export const FETCH_UNASSIGNED_STARTED = 'FETCH_UNASSIGNED_STARTED';
export const FETCH_UNASSIGNED_SUCCESS = 'FETCH_UNASSIGNED_SUCCESS';
export const FETCH_UNASSIGNED_ERROR = 'FETCH_UNASSIGNED_ERROR';