export const FETCH_ACTIVE_COURSES = 'COURSES/FETCH_ACTIVE_COURSES';
export const LOADING_ACTIVE_COURSES_STARTED = 'COURSES/LOADING_ACTIVE_STARTED';
export const LOADING_ACTIVE_COURSES_SUCCESS = 'COURSES/LOADING_ACTIVE_FINISHED';
export const LOADING_ACTIVE_COURSES_FAILED = 'COURSES/LOADING_ACTIVE_FAILED';

export const FETCH_NOT_ACTIVE_COURSES = 'COURSES/FETCH_NOT_ACTIVE_COURSES';
export const LOADING_NOT_ACTIVE_COURSES_STARTED = 'COURSES/LOADING_NOT_ACTIVE_STARTED';
export const LOADING_NOT_ACTIVE_COURSES_SUCCESS = 'COURSES/LOADING_NOT_ACTIVE_FINISHED';
export const LOADING_NOT_ACTIVE_COURSES_FAILED = 'COURSES/LOADING_NOT_ACTIVE_FAILED';

export const CREATE_COURSE = 'COURSES/CREATE_COURSE';
export const CREATING_COURSE_STARTED = 'COURSES/CREATING_STARTED';
export const CREATING_COURSE_SUCCESS = 'COURSES/CREATING_FINISHED';
export const CREATING_COURSE_FAILED = 'COURSES/CREATING_FAILED';

export const EDIT_COURSE = 'COURSES/EDIT_COURSE';
export const EDITING_COURSE_STARTED = 'COURSES/EDITING_STARTED';
export const EDITING_COURSE_SUCCESS = 'COURSES/EDITIGN_FINISHED';
export const EDITING_COURSE_FAILED = 'COURSES/EDITING_FAILED';

export const DELETE_COURSE = 'COURSES/DELETE_COURSE';
export const DELETING_COURSE_STARTED = 'COURSES/DELETING_STARTED';
export const DELETING_COURSE_SUCCESS = 'COURSES/DELETING_FINISHED';
export const DELETING_COURSE_FAILED = 'COURSES/DELETING_FAILED';

export const REACTIVATE_COURSE = 'COURSES/REACTIVATE_COURSE';
export const REACTIVATING_COURSE_STARTED = 'COURSES/REACTIVATING_STARTED';
export const REACTIVATING_COURSE_SUCCESS = 'COURSES/REACTIVATING_FINISHED';
export const REACTIVATING_COURSE_FAILED = 'COURSES/REACTIVATING_FAILED';

export const CLEAR_LOADED = 'COURSES/CLEAR_LOADED';
export const CLEAR_ERROR = 'COURSES/CLEAR_ERROR';
