export const FETCH_COURSES = 'COURSES/FETCH_COURSES';
export const LOADING_COURSES_STARTED = 'COURSES/LOADING_STARTED';
export const LOADING_COURSES_SUCCESS = 'COURSES/LOADING_FINISHED';
export const LOADING_COURSES_FAILED = 'COURSES/LOADING_FAILED';

export const CREATE_COURSE = 'COURSES/CREATE_COURSE';
export const CREATING_COURSE_STARTED = 'COURSES/CREATING_STARTED';
export const CREATING_COURSE_SUCCESS = 'COURSES/CREATING_FINISHED';
export const CREATING_COURSE_FAILED = 'COURSES/CREATING_FAILED';

export const EDIT_COURSE = 'COURSES/EDIT_COURSE';
export const EDITING_COURSE_STARTED = 'COURSES/EDITING_STARTED';
export const EDITING_COURSE_SUCCESS = 'COURSES/EDITIGN_FINISHED';
export const EDITING_COURSE_FAILED = 'COURSES/EDITING_FAILED';
export const EDITING_CLEAR_ERROR = 'COURSES/EDITING_CLEAR_ERROR';

export const CLEAR_LOADED = 'COURSES/CLEAR_LOADED';
