export const FETCH_LESSONS = 'LESSONS/FETCH_LESSONS';
export const LOADING_LESSONS_STARTED = 'LESSONS/LOADING_LESSONS_STARTED';
export const LOADING_LESSONS_FINISHED = 'LESSONS/LOADING_LESSONS_FINISHED';
export const LOADING_LESSONS_FAILED = 'LESSONS/LOADING_LESSONS_FAILED';

export const ADD_LESSON = 'LESSONS/ADD_LESSON';
export const ADDING_STARTED = 'LESSONS/ADDING_STARTED';
export const ADDING_FINISHED = 'LESSONS/ADDING_FINISHED ';
export const ADDING_FAILED = 'LESSONS/ADDING_FAILED';

export const EDIT_LESSON = 'LESSONS/EDIT_LESSON';
export const EDITING_STARTED = 'LESSONS/EDITING_STARTED';
export const EDITING_FINISHED = 'LESSONS/EDITING_FINISHED';
export const EDITING_FAILED = 'LESSONS/EDITING_FAILED';

export const LOAD_LESSONS_BY_STUDENT_ID = 'LESSONS/LOAD_LESSONS_BY_STUD_ID';
export const LOADING_LESSONS_BY_STUDENT_ID_STARTED = 'LESSONS/LOADING_BY_STUD_ID_STARTED';
export const LOADING_LESSONS_BY_STUDENT_ID_SUCCEED = 'LESSONS/LOADING_BY_STUD_ID_SUCCEED';
export const LOADING_LESSONS_BY_STUDENT_ID_FAILED = 'LESSONS/LOADING_BY_STUD_ID_FAILED';

export const LOAD_LESSON_BY_ID = 'LESSONS/LOAD_LESSON_BY_ID';
export const LOADING_LESSON_BY_ID_STARTED = 'LESSONS/LOADING_LESSON_BY_LESSON_ID_STARTED';
export const LOADING_LESSON_BY_ID_SUCCEED = 'LESSONS/LOADING_LESSON_BY_LESSON_ID_SUCCEED';
export const LOADING_LESSON_BY_ID_FAILED = 'LESSONS/LOADING_LESSON_BY_LESSON_ID_FAILED';

export const CLEAR_LOADED = 'LESSONS/CLEAR_LOADED';
export const CLEAR_ERROR = 'LESSONS/CLEAR_ERROR';
