export const GET_EVENT = 'GET_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const CONNECT_EVENT_TO_LESSON = 'CONNECT_EVENT_TO_LESSON';

export const LOADING_GET_EVENT_STARTED = 'LOADING_GET_EVENT_STARTED';
export const LOADING_GET_EVENT_SUCCESS = 'LOADING_GET_EVENT_SUCCESS';
export const LOADING_GET_EVENT_FAILED = 'LOADING_GET_EVENT_FAILED';

export const LOADING_UPDATE_EVENT_STARTED = 'LOADING_UPDATE_EVENT_STARTED';
export const LOADING_UPDATE_EVENT_SUCCESS = 'LOADING_UPDATE_EVENT_SUCCESS';
export const LOADING_UPDATE_EVENT_FAILED = 'LOADING_UPDATE_EVENT_FAILED';

export const LOADING_DELETE_EVENT_STARTED = 'LOADING_DELETE_EVENT_STARTED';
export const LOADING_DELETE_EVENT_SUCCESS = 'LOADING_DELETE_EVENT_SUCCESS';
export const LOADING_DELETE_EVENT_FAILED = 'LOADING_DELETE_EVENT_FAILED';

export const LOADING_CONNECT_EVENT_STARTED = 'LOADING_CONNECT_EVENT_STARTED';
export const LOADING_CONNECT_EVENT_SUCCESS = 'LOADING_CONNECT_EVENT_SUCCESS';
export const LOADING_CONNECT_EVENT_FAILED = 'LOADING_CONNECT_EVENT_FAILED';
