export const FETCH_SECRETARIES = 'SECRETARY/FETCH_SECRETARIES';
export const SECRETARIES_LOADING_STARTED = 'SECRETARY/SECRETARIES_LOADING_STARTED';
export const SECRETARIES_LOADING_SUCCESS = 'SECRETARY/SECRETARIES_LOADING_SUCCESS';
export const SECRETARIES_LOADING_FAILED = 'SECRETARY/SECRETARIES_LOADING_FAILED';

export const CREATE_SECRETARY = 'SECRETARY/CREATE_SECRETARY';
export const SECRETARY_CREATING_STARTED = 'SECRETARY/SECRETARY_CREATING_STARTED';
export const SECRETARY_CREATING_SUCCESS = 'SECRETARY/SECRETARY_CREATING_SUCCESS';
export const SECRETARY_CREATING_FAILED = 'SECRETARY/SECRETARY_CREATING_FAILED';

export const UPDATE_SECRETARY = 'SECRETARY/UPDATE_SECRETARY';
export const SECRETARY_UPDATING_STARTED = 'SECRETARY/SECRETARY_UPDATING_STARTED';
export const SECRETARY_UPDATING_SUCCESS = 'SECRETARY/SECRETARY_UPDATING_SUCCESS';
export const SECRETARY_UPDATING_FAILED = 'SECRETARY/SECRETARY_UPDATING_FAILED';

export const DELETE_SECRETARY = 'SECRETARY/UPDATE_SECRETARIES';
export const SECRETARY_DELETING_STARTED = 'SECRETARY/SECRETARY_DELETING_STARTED';
export const SECRETARY_DELETING_SUCCESS = 'SECRETARY/SECRETARY_DELETING_SUCCESS';
export const SECRETARY_DELETING_FAILED = 'SECRETARY/SECRETARY_DELETING_FAILED';