export const FETCH_SCHEDULES = 'SCHEDULES/FETCH_SCHEDULES';
export const LOADING_SCHEDULES_STARTED = 'SCHEDULES/LOADING_SCHEDULES_STARTED'
export const LOADING_SCHEDULES_SUCCESS = 'SCHEDULES/LOADING_SCHEDULES_FINISHED';
export const LOADING_SCHEDULES_FAILED = 'SCHEDULES/LOADING_SCHEDULES_FAILED';

export const FETCH_SCHEDULES_BY_GROUPID = 'SCHEDULES/FETCH_SCHEDULES_BY_GROUPID';
export const LOADING_SCHEDULES_BY_GROUPID_STARTED = 'SCHEDULES/LOADING_SCHEDULES_BY_GROUPID_STARTED'
export const LOADING_SCHEDULES_BY_GROUPID_SUCCESS = 'SCHEDULES/LOADING_SCHEDULES_BY_GROUPID_FINISHED';
export const LOADING_SCHEDULES_BY_GROUPID_FAILED = 'SCHEDULES/LOADING_SCHEDULES_BY_GROUPID_FAILED';

export const CREATE_SCHEDULE = 'SCHEDULES/CREATE_SCHEDULE';
export const CREATING_SCHEDULE_STARTED = 'SCHEDULES/CREATING_STARTED';
export const CREATING_SCHEDULE_SUCCESS = 'SCHEDULES/CREATING_FINISHED';
export const CREATING_SCHEDULE_FAILED = 'SCHEDULES/CREATING_FAILED';

export const EDIT_SCHEDULE = 'SCHEDULES/EDIT_SCHEDULE';
export const EDITING_SCHEDULE_STARTED = 'SCHEDULES/EDITING_STARTED';
export const EDITING_SCHEDULE_SUCCESS = 'SCHEDULES/EDITING_FINISHED';
export const EDITING_SCHEDULE_FAILED = 'SCHEDULES/EDITING_FAILED';

export const DELETE_SCHEDULE = 'SCHEDULES/DELETE_SCHEDULE';
export const DELETING_SCHEDULE_STARTED = 'SCHEDULES/DELETING_STARTED';
export const DELETING_SCHEDULE_SUCCESS = 'SCHEDULES/DELETING_FINISHED';
export const DELETING_SCHEDULE_FAILED = 'SCHEDULES/DELETING_FAILED';

export const CLEAR_LOADED = 'SCHEDULES/CLEAR_LOADED';