export const data = [
  {
    id: 1,
    themeName: 'Introduction',
    mentorId: 2,
    studentGroupId: 1,
    lessonVisits: [
      {
        studentId: 0,
        studentMark: 2,
        presence: false,
        comment: 'Good',
      },
      {
        studentId: 1,
        studentMark: 2,
        presence: false,
        comment: 'Good',
      },
      {
        studentId: 4,
        studentMark: 4,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 5,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 7,
        studentMark: 3,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 8,
        studentMark: 2,
        presence: false,
        comment: 'Good',
      },
      {
        studentId: 9,
        studentMark: 2,
        presence: false,
        comment: 'Good',
      },
      {
        studentId: 12,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 13,
        studentMark: 4,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 15,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 16,
        studentMark: 4,
        presence: true,
        comment: 'Good',
      },
    ],
    lessonDate: '2020-11-04 11:20:00',
  },
  {
    id: 2,
    themeName: 'Types',
    mentorId: 2,
    studentGroupId: 2,
    lessonVisits: [
      {
        studentId: 1,
        studentMark: 2,
        presence: false,
        comment: 'Good',
      },
      {
        studentId: 3,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 4,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 6,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 7,
        studentMark: 3,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 8,
        studentMark: 3,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 10,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 11,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 12,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 13,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 14,
        studentMark: 5,
        presence: true,
        comment: 'Good',
      },
      {
        studentId: 16,
        studentMark: 4,
        presence: true,
        comment: 'Good',
      },
    ],
    lessonDate: '2020-11-06 12:20:00',
  },
];