export const GET_THEMES = 'THEMES/GET_THEMES';
export const LOADING_THEMES_STARTED = 'THEMES/LOADING_STARTED'
export const LOADING_THEMES_SUCCESS = 'THEMES/LOADING_FINISHED';
export const LOADING_THEMES_FAILED = 'THEMES/LOADING_FAILED';

export const CREATE_THEME = 'THEMES/CREATE_COURSE';
export const CREATING_THEME_STARTED = 'THEMES/CREATING_STARTED';
export const CREATING_THEME_SUCCESS = 'THEMES/CREATING_FINISHED';
export const CREATING_THEME_FAILED = 'THEMES/CREATING_FAILED';

export const EDIT_THEME = 'THEMES/EDIT_COURSE';
export const EDITING_THEME_STARTED = 'THEMES/EDITING_STARTED';
export const EDITING_THEME_SUCCESS = 'THEMES/EDITIGN_FINISHED';
export const EDITING_THEME_FAILED = 'THEMES/EDITING_FAILED';

export const DELETE_THEME = 'THEMES/DELETE_THEME';
export const DELETING_THEME_STARTED = 'THEMES/DELETING_STARTED';
export const DELETING_THEME_SUCCESS = 'THEMES/DELETING_FINISHED';
export const DELETING_THEME_FAILED = 'THEMES/DELETING_FAILED';